# Generated by Django 5.2.1 on 2025-06-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patsumapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tel',
            name='phone',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
